registers: Add bitset class to replace std implementation
JPTIZ/libgba-cpp pull request #16
Opened 2021-05-25 01:09 UTC by patrickelectric

std::bitset does not use the same space as the necessary for the N bits,
with that we can't use the new operator to force the usage of a memory
address.

The new implementation fix that issue.

PS: I dont know if bitset should exist under registers.

2021-05-25 04:49 UTC, JPTIZ commented
> PS: I dont know if bitset should exist under registers.

Hm, interesting, could you clarify why exactly?

2021-05-25 11:59 UTC, patrickelectric commented
> > PS: I dont know if bitset should exist under registers.
> 
> Hm, interesting, could you clarify why exactly?

Well, is your library :laughing: 
Should be this type be available under a header for itself ? Or maybe in a special namespace for future usage, like `gba::std::bitset`  ?

I'm ok to have it in registers for now, but let me know what you think.

2021-05-25 13:56 UTC, JPTIZ commented
> > > PS: I dont know if bitset should exist under registers.
> > 
> > 
> > Hm, interesting, could you clarify why exactly?
> 
> Well, is your library laughing
> Should this type be available under a header for itself ? Or maybe in a special namespace for future usage, like `gba::std::bitset` ?
> 
> I'm ok to have it in registers for now, but let me know what you think.

Oh okay, registers = the registers library. I thought you were saying that using bitset to abstract registers was a bad idea :) I think a header itself would be interesting, under `libgba/utils/bitset.h` or `libgba/bitset.h`.

2021-05-30 19:35 UTC, JPTIZ requested changes
Just update the bitset implementation's header and it'll be approved.

2021-05-31 19:58 UTC, patrickelectric commented
Sorry, I'm in the middle of a trip, will update the patch asap.

2021-12-24 22:44 UTC, JPTIZ commented
I'll merge it as is and later submit a quick patch moving the header location :)

2021-12-24 22:44 UTC, merged

2021-12-25 00:07 UTC, patrickelectric commented
Merry Christmas!

On Fri, Dec 24, 2021, 10:44 PM João Paulo Taylor Ienczak Zanette <
***@***.***> wrote:

> Merged #16 <https://github.com/JPTIZ/libgba-cpp/pull/16> into master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JPTIZ/libgba-cpp/pull/16#event-5814381381>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJIYCJAVJITL53LJZNENTTUSTZULANCNFSM45OHUIRQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>